# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+TITLE: Article Title
#+AUTHOR: Lucas Mello Schnorr

#+STARTUP: overview indent
#+LANGUAGE: en
#+OPTIONS: H:3 creator:nil timestamp:nil skip:nil toc:nil num:t ^:nil ~:~
#+OPTIONS: author:nil title:nil date:nil
#+TAGS: noexport(n) deprecated(d) ignore(i)
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport

#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [12pt]

#+LATEX_HEADER: \sloppy
#+LATEX_HEADER: \usepackage{algorithm}
#+LATEX_HEADER: \usepackage{algpseudocode}

# PDF generation can be done by make (thanks Luka Stanisic)
#   or C-c C-e l p (thanks Vinicius Garcia)

* *The Paper*                                                       :ignore:
** Frontpage                                                        :ignore:

#+BEGIN_EXPORT latex
\makeatletter
\let\orgtitle\@title
\makeatother

\title{\orgtitle}

\author{
   Lucas Mello Schnorr\inst{1},
   Somebody Else\inst{2}}

\address{
   Institute of Informatics, Federal University of Rio Grande do Sul (UFRGS)\\
   Caixa Postal 15.064 -- 91.501-970 -- Porto Alegre -- RS -- Brazil
   \nextinstitute
   Somebody else's Institution,
   Adress --  Brazil
   \email{schnorr@inf.ufrgs.br}}
#+END_EXPORT

#+LaTeX: \maketitle

** Abstract                                                         :ignore:

#+begin_abstract
Put the abstract here.
#+end_abstract

#+begin_resumo
Coloque o resumo aqui.
#+end_resumo

** Introduction

This is just an example to show how Orgmode cite:orgmode can be
neatly used to write papers following the SBC Article latex style. Feel
free to modify and distributed this as you wish.

Be aware that this example is compatible with OrgMode 9.*. Earlier or
later OrgMode versions require minor modifications to the Makefile
and/or ieee.org files.

For a detailed explanation on why and how to write reproducible
articles using OrgMode, please visit the following [[https://github.com/alegrand/RR_webinars/blob/master/1_replicable_article_laboratory_notebook/index.org][page]].

** Apresentação do Algoritmo
*** Explicação do Algoritmo
O algoritmo Q-Learning é um método de aprendizado por reforço no qual um agente aprende a alcançar um objetivo final utilizando uma tabela chamada Q-Table. Essa tabela armazena valores para cada par de estado e ação, indicando o quão boa é determinada ação em um estado específico. Com base nesses valores, o agente tende a escolher as ações que possuem as maiores recompensas esperadas.

Para construir essa tabela, o agente precisa passar por um processo de treinamento composto por vários episódios. Em cada episódio, o agente executa uma sequência de passos (steps). A cada passo, uma ação é escolhida, o ambiente retorna uma recompensa, e o valor correspondente na Q-Table é atualizado. Ao longo do treinamento, o agente aprende quais ações produzem os melhores resultados para alcançar o objetivo desejado.

*** Problema Escolhido
O algoritmo Q-Learning foi escolhido para resolver um problema de pathfinding em um mundo em formato de grade. O desafio consiste em fazer um agente chegar ao ponto final utilizando apenas quatro ações de movimento: mover-se para cima, para baixo, para a esquerda e para a direita.

*** Pseudocódigo

#+begin_export latex
\begin{algorithm}
\caption{Q-Learning Sequencial}
\begin{algorithmic}[1]
\Require Grid$(L, C)$, Obstáculos$(O)$, Episódios$(E)$, Max\_Passos$(P)$
\Require $\alpha$ (Aprendizado), $\gamma$ (Desconto), $\varepsilon$ (Exploração)
\Statex \textbf{1. INICIALIZAÇÃO E AMBIENTE}
\State Alocar dinamicamente $Q\_Table[\text{Estados}][\text{Ações}]$
\State Preencher $Q\_Table$ com zeros
\State Gerar Grid$(L, C)$ com Estado\_Inicial $s_0$ em $(0,0)$, Estado\_Objetivo $g$ em $(L{-}1, C{-}1)$
\State \hspace{1.5em} e posicionar $O$ obstáculos aleatórios (evitando $s_0$ e $g$)
\State Configurar Recompensas: $R_{\text{objetivo}}(+100)$, $R_{\text{obstáculo}}(-100)$, $R_{\text{passo}}(-1)$, $R_{\text{loop}}(-10)$
\Statex \textbf{2. NÚCLEO DE APRENDIZADO (Treinamento)}
\For{cada episódio de $1$ até $E$}
  \State $s \leftarrow s_0$ (Estado Inicial)
  \For{cada passo de $1$ até $P$}
    \State \textit{// Seleção de Ação ($\varepsilon$-Greedy)}
    \If{$\text{Random}(0, 1) < \varepsilon$}
      \State $a \leftarrow \text{Escolher\_Ação\_Aleatória()}$
    \Else
      \State $a \leftarrow \arg\max_{a'} Q[s][a']$ (Melhor ação conhecida)
    \EndIf
    \State \textit{// Interação com o Ambiente}
    \State $s' \leftarrow \text{Calcular\_Próximo\_Estado}(s, a)$
    \State $r \leftarrow \text{Avaliar\_Recompensa}(s')$
    \If{$s'$ já foi visitado neste episódio}
      \State $r \leftarrow r + R_{\text{loop}}$ \Comment{Penalidade de ciclo}
    \EndIf
    \State \textit{// Atualização de Bellman (Aprendizado Temporal)}
    \State $\text{Max\_Q\_Futuro} \leftarrow \text{Máximo}(Q[s'][\text{todas\_ações}])$
    \State $Q[s][a] \leftarrow Q[s][a] + \alpha \cdot (r + \gamma \cdot \text{Max\_Q\_Futuro} - Q[s][a])$
    \State \textit{// Transição de Estado}
    \State $s \leftarrow s'$
    \If{$s = g$}
      \State Encerrar Episódio (Objetivo Alcançado)
    \EndIf
  \EndFor
\EndFor
\Statex \textbf{3. PÓS-PROCESSAMENTO E SAÍDA}
\State Política\_Ótima $\pi(s) \leftarrow \arg\max_a Q[s][a]$
\State Imprimir Visualização do Grid com $\pi(s)$
\State Simular Caminho Final do Agente
\State Liberar Memória Alocada
\end{algorithmic}
\end{algorithm}
#+end_export

** Possibilidade de Paralelização
Com base no código do Q-Learning sequencial, foram identificadas três possíveis abordagens de paralelização:

- Paralelização da obtenção da melhor ação;
- Paralelização dos steps;
- Paralelização dos episódios.

A paralelização da obtenção da melhor ação foi descartada, pois o número de ações disponíveis para o agente é relativamente pequeno, não proporcionando ganho de desempenho significativo que justificasse o custo da paralelização.

A paralelização dos steps também foi descartada, uma vez que cada step depende diretamente do estado atual, e o estado atual é resultado da ação executada no step anterior. Dessa forma, existe uma dependência verdadeira entre as execuções, tornando necessária a sincronização entre as threads e reduzindo os benefícios da paralelização.

Por fim, a paralelização dos episódios foi escolhida como a abordagem mais adequada, pois cada episódio pode ser executado de forma independente. Isso reduz problemas de dependência entre threads e permite melhor aproveitamento do paralelismo durante o treinamento do agente.

** Maneiras de Paralelizar os Episódios
Como dito anteriormente, a paralelização dos episódios foi escolhida como a mais adequada, porém existe duas possíveis de parelizar os episódios:
- A primeira maneira é que cada thread vai ter sua Q-Table Local e dado tantos episódios, vai sincronizar com a Q-Table Global (a que será aprendida no final);
- A segunda maneira é que cada thread vai acessar e atualizar diretamente na Q-Table Global. Esse método é chamado de HogWild;

*** Com Sincronização

*** Hogwild

** Background and Experimental Context
<<sec.context>>
*** Background
<<sec.background>>
*** Experimental Context and Workload Details
<<sec.setup>>
** Related Work and Motivation
<<sec.relatedwork>>

Check this paper cite:schnorr2013visualizing about how you need to
semantically aggregate data.

** Your Great Contribution to Computer Science
<<sec.proposal>>
** Your Super Results
** Conclusion
** Acknowledgments
:PROPERTIES:
:UNNUMBERED: t
:END:

Who paid for this?

** References                                                        :ignore:

# See next section to understand how refs.bib file is created.
bibliographystyle:sbc.bst
[[bibliography:refs.bib]]

* Bib file is here                                                 :noexport:

Tangle this file with C-c C-v t
#+begin_src bibtex :tangle refs.bib
@article{orgmode,
  author =	"Eric Schulte and Dan Davison and Thomas Dye and Carsten Dominik",
  title =	"A Multi-Language Computing Environment for Literate Programming and Reproducible Research",
  journal =	"J. of Stat. Soft.",
  volume =	"46",
  number =	"3",
  day =  	"25",
  year = 	"2012",
  CODEN =	"JSSOBK",
  ISSN = 	"1548-7660",
  bibdate =	"2011-10-03",
  accepted =	"2011-10-03",
  acknowledgement = "",
  submitted =	"2010-12-22",
}

@incollection{schnorr2013visualizing,
  title={Visualizing More Performance Data Than What Fits on Your Screen},
  author={Schnorr, Lucas M and Legrand, Arnaud},
  booktitle={Tools for High Performance Computing 2012},
  pages={149--162},
  year={2013},
  publisher={Springer}
}
#+end_src
* Emacs setup                                                      :noexport:
# Local Variables:
# eval: (add-to-list 'load-path ".")
# eval: (require 'ox-extra)
# eval: (ox-extras-activate '(ignore-headlines))
# eval: (require 'org-ref)
# eval: (require 'doi-utils)
# eval: (add-to-list 'org-latex-packages-alist '("" "url") t)
# eval: (add-to-list 'org-latex-packages-alist '("" "sbc-template") t)
# eval: (add-to-list 'org-latex-packages-alist '("AUTO" "babel" t ("pdflatex")))
# eval: (setq org-latex-pdf-process (list "latexmk -pdf %f"))
# eval: (add-to-list 'org-export-before-processing-hook (lambda (be) (org-babel-tangle)))
# End:
