# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+TITLE: Article Title
#+AUTHOR: Lucas Mello Schnorr

#+STARTUP: overview indent
#+LANGUAGE: en
#+OPTIONS: H:3 creator:nil timestamp:nil skip:nil toc:nil num:t ^:nil ~:~
#+OPTIONS: author:nil title:nil date:nil
#+TAGS: noexport(n) deprecated(d) ignore(i)
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport

#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [12pt]

#+LATEX_HEADER: \sloppy
#+LATEX_HEADER: \usepackage{algorithm}
#+LATEX_HEADER: \usepackage{algpseudocode}

# PDF generation can be done by make (thanks Luka Stanisic)
#   or C-c C-e l p (thanks Vinicius Garcia)

* *The Paper*                                                       :ignore:
** Frontpage                                                        :ignore:

#+BEGIN_EXPORT latex
\makeatletter
\let\orgtitle\@title
\makeatother

\title{\orgtitle}

\author{
   Lucas Mello Schnorr\inst{1},
   Somebody Else\inst{2}}

\address{
   Institute of Informatics, Federal University of Rio Grande do Sul (UFRGS)\\
   Caixa Postal 15.064 -- 91.501-970 -- Porto Alegre -- RS -- Brazil
kk   \nextinstitute
   Somebody else's Institution,
   Adress --  Brazil
   \email{schnorr@inf.ufrgs.br}}
#+END_EXPORT

#+LaTeX: \maketitle

** Abstract                                                         :ignore:

#+begin_abstract
Put the abstract here.
#+end_abstract

#+begin_resumo
Coloque o resumo aqui.
#+end_resumo

** Introduction

This is just an example to show how Orgmode cite:orgmode can be
neatly used to write papers following the SBC Article latex style. Feel
free to modify and distributed this as you wish.

Be aware that this example is compatible with OrgMode 9.*. Earlier or
later OrgMode versions require minor modifications to the Makefile
and/or ieee.org files.

For a detailed explanation on why and how to write reproducible
articles using OrgMode, please visit the following [[https://github.com/alegrand/RR_webinars/blob/master/1_replicable_article_laboratory_notebook/index.org][page]].

** Apresentação do Algoritmo
*** Explicação do Algoritmo
O algoritmo Q-Learning é um método de aprendizado por reforço no qual um agente aprende a alcançar um objetivo final utilizando uma tabela chamada Q-Table. Essa tabela armazena valores para cada par de estado e ação, indicando o quão boa é determinada ação em um estado específico. Com base nesses valores, o agente tende a escolher as ações que possuem as maiores recompensas esperadas.

Para construir essa tabela, o agente precisa passar por um processo de treinamento composto por vários episódios. Em cada episódio, o agente executa uma sequência de passos (steps). A cada passo, uma ação é escolhida, o ambiente retorna uma recompensa, e o valor correspondente na Q-Table é atualizado. Ao longo do treinamento, o agente aprende quais ações produzem os melhores resultados para alcançar o objetivo desejado.

*** Problema Escolhido
O algoritmo Q-Learning foi escolhido para resolver um problema de pathfinding em um mundo em formato de grade. O desafio consiste em fazer um agente chegar ao ponto final utilizando apenas quatro ações de movimento: mover-se para cima, para baixo, para a esquerda e para a direita.

*** Pseudocódigo

#+begin_example
    1 ALGORITMO: Q-Learning Sequencial
    2 -------------------------------------------------------------------------
    3 ENTRADAS:
    4     Grid(L, C), Obstáculos(O), Episódios(E), Max_Passos(P)
    5     alfa (Aprendizado), gama (Desconto), epsilon (Exploração)
    6
    7 1. INICIALIZAÇÃO E AMBIENTE
    8    |  Alocar dinamicamente Q_Table[Estados][Ações]
    9    |  Preencher Q_Table com zeros
   10    |  Gerar Grid(L, C) com:
   11    |    - Estado_Inicial s0 em (0, 0)
   12    |    - Estado_Objetivo g em (L-1, C-1)
   13    |    - Posicionar O obstáculos aleatórios (evitando s0 e g)
   14    |  Configurar Recompensas:
   15    |    - R_objetivo (+100)
   16    |    - R_obstáculo (-100)
   17    |    - R_passo (-1)
   18    |    - R_loop (-10)
   19
   20 2. NUCLEO DE APRENDIZADO (Treinamento)
   21    |  PARA cada episódio de 1 até E:
   22    |  |  s <- s0 (Estado Inicial)
   23    |  |  PARA cada passo de 1 até P:
   24    |  |  |
   25    |  |  |  // Seleção de Ação (epsilon-Greedy)
   26    |  |  |  SE Random(0, 1) < epsilon ENTÃO:
   27    |  |  |  |  a <- Escolher_Ação_Aleatória()
   28    |  |  |  SENÃO:
   29    |  |  |  |  a <- argmax_a' Q[s][a'] (Melhor ação conhecida)
   30    |  |  |
   31    |  |  |  // Interação com o Ambiente
   32    |  |  |  s' <- Calcular_Próximo_Estado(s, a)
   33    |  |  |  r  <- Avaliar_Recompensa(s')
   34    |  |  |
   35    |  |  |  SE s' já foi visitado neste episódio ENTÃO:
   36    |  |  |  |  r <- r + R_loop  // Penalidade de ciclo
   37    |  |  |
   38    |  |  |  // Atualização de Bellman (Aprendizado Temporal)
   39    |  |  |  Max_Q_Futuro <- Máximo(Q[s'][todas_ações])
   40    |  |  |  Q[s][a] <- Q[s][a] + alfa * (r + gama * Max_Q_Futuro - Q[s][a])
   41    |  |  |
   42    |  |  |  // Transição de Estado
   43    |  |  |  s <- s'
   44    |  |  |
   45    |  |  |  SE s == g ENTÃO:
   46    |  |  |  |  Encerrar Episódio (Objetivo Alcançado)
   47    |  |  FIM PARA
   48    |  FIM PARA
   49
   50 3. POS-PROCESSAMENTO E SAÍDA
   51    |  Política_Ótima pi(s) <- argmax_a Q[s][a]
   52    |  Imprimir Visualização do Grid com pi(s)
   53    |  Simular Caminho Final do Agente
   54    |  Liberar Memória Alocada
   55 -------------------------------------------------------------------------
#+end_example

** Possibilidade de Paralelização
Com base no código do Q-Learning sequencial, foram identificadas três possíveis abordagens de paralelização:

- Paralelização da obtenção da melhor ação;
- Paralelização dos steps;
- Paralelização dos episódios.

A paralelização da obtenção da melhor ação foi descartada, pois o número de ações disponíveis para o agente é relativamente pequeno, não proporcionando ganho de desempenho significativo que justificasse o custo da paralelização.

A paralelização dos steps também foi descartada, uma vez que cada step depende diretamente do estado atual, e o estado atual é resultado da ação executada no step anterior. Dessa forma, existe uma dependência verdadeira entre as execuções, tornando necessária a sincronização entre as threads e reduzindo os benefícios da paralelização.

Por fim, a paralelização dos episódios foi escolhida como a abordagem mais adequada, pois cada episódio pode ser executado de forma independente. Isso reduz problemas de dependência entre threads e permite melhor aproveitamento do paralelismo durante o treinamento do agente.

** Maneiras de Paralelizar os Episódios
Como dito anteriormente, a paralelização dos episódios foi escolhida como a mais adequada, porém existe duas possíveis de parelizar os episódios:
- A primeira maneira é que cada thread vai ter sua Q-Table Local e dado tantos episódios, vai sincronizar com a Q-Table Global (a que será aprendida no final);
- A segunda maneira é que cada thread vai acessar e atualizar diretamente na Q-Table Global. Esse método é chamado de HogWild;

*** Com Sincronização

*** HOGWILD!
HOGWILD! é um 'update scheme' alternativo que pode ser utilizado ao paralelizar Stochastic Gradient Descent (SGDs) sem utilizar locks. Esse update scheme permite que processadores acessem uma memória compartilhada, introduzindo a possibilidade de sobrescrever o trabalho de outro processador. O artigo a seguir \href{https://arxiv.org/pdf/1106.5730}{Hogwild!: A Lock-Free Approach to Parallelizing Stochastic Gradient Descent} demonstra experimentalmente que HOGWILD! supera outros 'schemes' que usam locking em ordens de magnitude. 
Decidimos utilizar abordagem para diversificar os resultados e proporcionar uma base de dados mais rica para a análise.
A função train_hogwild faz com que cada thread amostre uniformemente
os episódios do espaço de treinamento, calcula o gradiente (via
equação de Bellman), e escreve na q_table compartilhada sem nenhum
lock. O schedule(dynamic) mapeia para a ideia do artigo de que os
processadores devem pegar trabalho sob demanda para evitar que
concentrem atualizações na mesma região do espaço de estados.

** Background and Experimental Context
<<sec.context>>
*** Background
<<sec.background>>
*** Experimental Context and Workload Details
<<sec.setup>>
** Related Work and Motivation
<<sec.relatedwork>>

Check this paper cite:schnorr2013visualizing about how you need to
semantically aggregate data.

** Your Great Contribution to Computer Science
<<sec.proposal>>
** Your Super Results
** Conclusion
** Acknowledgments
:PROPERTIES:
:UNNUMBERED: t
:END:

Who paid for this?

** References                                                        :ignore:

# See next section to understand how refs.bib file is created.
bibliographystyle:sbc.bst
[[bibliography:refs.bib]]

* Bib file is here                                                 :noexport:

Tangle this file with C-c C-v t
#+begin_src bibtex :tangle refs.bib
@article{orgmode,
  author =	"Eric Schulte and Dan Davison and Thomas Dye and Carsten Dominik",
  title =	"A Multi-Language Computing Environment for Literate Programming and Reproducible Research",
  journal =	"J. of Stat. Soft.",
  volume =	"46",
  number =	"3",
  day =  	"25",
  year = 	"2012",
  CODEN =	"JSSOBK",
  ISSN = 	"1548-7660",
  bibdate =	"2011-10-03",
  accepted =	"2011-10-03",
  acknowledgement = "",
  submitted =	"2010-12-22",
}

@incollection{schnorr2013visualizing,
  title={Visualizing More Performance Data Than What Fits on Your Screen},
  author={Schnorr, Lucas M and Legrand, Arnaud},
  booktitle={Tools for High Performance Computing 2012},
  pages={149--162},
  year={2013},
  publisher={Springer}
}
#+end_src
* Emacs setup                                                      :noexport:
# Local Variables:
# eval: (add-to-list 'load-path ".")
# eval: (require 'ox-extra)
# eval: (ox-extras-activate '(ignore-headlines))
# eval: (require 'org-ref)
# eval: (require 'doi-utils)
# eval: (add-to-list 'org-latex-packages-alist '("" "url") t)
# eval: (add-to-list 'org-latex-packages-alist '("" "sbc-template") t)
# eval: (add-to-list 'org-latex-packages-alist '("AUTO" "babel" t ("pdflatex")))
# eval: (setq org-latex-pdf-process (list "latexmk -pdf %f"))
# eval: (add-to-list 'org-export-before-processing-hook (lambda (be) (org-babel-tangle)))
# End:
